const ELEMENTS = {
  books: {
    modes: false,
    size: 0.14,
    position: { top: 34, left: 9 },
    tiles: 1,
    range: { min: 0, max: 0 },
    src: ["books"],
  },
  mirror: {
    modes: false,
    size: 0.13,
    position: { top: 35, left: 35 },
    tiles: 1,
    range: { min: 0, max: 0 },
    src: ["mirror"],
  },
  piano: {
    modes: false,
    size: 0.35,
    position: { top: 50, left: 35 },
    tiles: 1,
    range: { min: 0, max: 0 },
    src: ["piano"],
  },
  speaker: {
    modes: false,
    size: 0.18,
    position: { top: 53, left: 45 },
    tiles: 1,
    range: { min: 0, max: 0 },
    src: ["speaker"],
  },
  lamp: {
    modes: true,
    size: 0.5,
    position: { top: 35, left: 60 },
    tiles: 1,
    range: { min: 0, max: 0 },
    src: ["lampDay", "lampNight"],
  },
  fish: {
    modes: false,
    size: 0.15,
    position: { top: 60, left: 92 },
    tiles: 1,
    range: { min: 0, max: 0 },
    src: ["fish"],
  },
  seeds: {
    modes: false,
    size: 0.08,
    position: { top: 39.5, left: 77 },
    tiles: 4,
    range: { min: 0, max: 12 },
    src: ["seeds"],
  },
  computer: {
    modes: true,
    size: 0.22,
    position: { top: 55, left: 35 },
    tiles: 1,
    range: { min: 0, max: 0 },
    src: ["computerDay", "computerNight"],
  },
};

export { ELEMENTS };
